apiVersion: v1
kind: Secret
metadata:
  name: higress-plugin-server
  namespace: higress-system
type: Opaque
stringData:
  upload-token: change-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: higress-plugin-server
  namespace: higress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: higress-plugin-server
  template:
    metadata:
      labels:
        app: higress-plugin-server
    spec:
      containers:
        - name: plugin-server
          image: {image-address}
          env:
            - name: PLUGIN_SERVER_UPLOAD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: higress-plugin-server
                  key: upload-token
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - higress-plugin-server
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: higress-plugin-server
  namespace: higress-system
spec:
  selector:
    app: higress-plugin-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
